name: Code quality

on:
  pull_request:
    branches:
      - "main"
      - "*/main/*/**"
  push:
    branches:
      - "main"
      - "*/main/*/**"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome check --no-errors-on-unmatched --files-ignore-unknown=true $(git diff --name-only "${GITHUB_REF}")
